export enum RepositoryEnum {
  PRODUCT_REPOSITORY = "PROCUCT_REPOSITORY",
  CATEGORY_REPOSITORY = " CATEGORY_REPOSITORY",
  EMPRESA_REPOSITORY = "EMPRESA_REPOSITORY",
  EMPLEADO_REPOSITORY = "EMPLEADO_REPOSITORY"
}